In [ ]:
import numpy as np
#Дорошко Денис - Д5 О16 Р18 О16 Ш26 О16 К12 О16 Д5 Е6 Н15 И10 С19
matrix = np.array(
[[0, 5, 16, 18, 16],
 [5, 0,26, 16, 12],
 [16, 26, 0, 16, 5],
 [18, 16, 16, 0, 6],
 [16, 12, 5, 6, 0]])
#matrix = np.array(
# [[0, 10, 3, 1, 15],
# [10, 0,16, 3, 17],
# [3, 16, 0, 6, 20],
# [1, 3, 6, 0, 18],
# [15, 17, 20, 18, 0]])
def make_matrix(size, seed=23):
 np.random.seed(seed)
 rand_matrix = np.zeros((size, size))
 for i in range(size):
  for j in range(i, size):
    rand_matrix[i, j] = np.random.randint(0, 50)
    rand_matrix[j, i] = rand_matrix[i, j]
 return rand_matrix

#matrix = make_matrix(10)
print(matrix)

[[ 0  5 16 18 16]
 [ 5  0 26 16 12]
 [16 26  0 16  5]
 [18 16 16  0  6]
 [16 12  5  6  0]]


In [ ]:
def eager_algorithm(matrix):
 looked_rows = []
 path = []
 path_length = 0
 current_row = 0
 for i in range(matrix.shape[0]):
   first_available = 0
   for j in range(matrix.shape[1]):
     if(j != current_row and j not in looked_rows):
       first_available = j
       break
   min_column = matrix[current_row, first_available]
   min_col_pos = first_available
   for j in range(first_available + 1, matrix.shape[1]):
    if(j not in looked_rows and current_row != j and matrix[current_row, j] < min_column):
      min_column = matrix[current_row, j]
      min_col_pos = j
   path_length += min_column
   path.append(current_row)
   looked_rows.append(current_row)
   current_row = min_col_pos
 path.append(path[0])
 return (path, path_length)

In [ ]:
def permutations(iterable):
    pool = tuple(iterable)
    n = len(pool)
    r = n
    if r > n:
        return
    indices = list(range(n))
    cycles = list(range(n, n-r, -1))
    yield tuple(pool[i] for i in indices[:r])
    while n:
        for i in reversed(range(r)):
            cycles[i] -= 1
            if cycles[i] == 0:
                indices[i:] = indices[i+1:] + indices[i:i+1]
                cycles[i] = n - i
            else:
                j = cycles[i]
                indices[i], indices[-j] = indices[-j], indices[i]
                yield tuple(pool[i] for i in indices[:r])
                break
        else:
            return
def full_search(matrix):
  permutationItems = permutations([i for i in range(matrix.shape[0])])
  paths = []
  times = []
  for path in permutationItems:
    paths.append(path)
    times.append([])
    for i in range(matrix.shape[0]):
      time = matrix[path[i],path[0]]
      if i < matrix.shape[0] - 1:
        time = matrix[path[i],path[i + 1]]
      times[-1].append(time)
  return paths,times

def find_min_path(matrix):
  paths,times = full_search(matrix)
  min_path = sum(times[0])
  min_pos = 0
  for i in range(1, len(paths)):
    next_sum = sum(times[i])
    if next_sum < min_path:
      min_path = next_sum
      min_pos = i
  full_path = list(paths[min_pos])
  full_path.append(paths[min_pos][0])
  return min_path,full_path

def find_max_path(matrix):
  paths,times = full_search(matrix)
  max_path = sum(times[0])
  max_pos = 0
  for i in range(1, len(paths)):
    next_sum = sum(times[i])
    if next_sum > max_path:
      max_path = next_sum
      max_pos = i
  full_path = list(paths[max_pos])
  full_path.append(paths[max_pos][0])
  return max_path,full_path

  



In [ ]:
#Дорошко Денис - Д5 О16 Р18 О16 Ш26 О16 К12 О16 Д5 Е6 Н15 И10 С19
matrix = np.array(
[[0, 5, 16, 18, 16],
 [5, 0,26, 16, 12],
 [16, 26, 0, 16, 5],
 [18, 16, 16, 0, 6],
 [16, 12, 5, 6, 0]])
eager_path,min_eager = eager_algorithm(matrix)
print("Eager value:" + str(min_eager) + " and path:" + str(eager_path))
min_path_len,min_path = find_min_path(matrix)
print("Min by search:" + str(min_path_len) + " and path:" + str(min_path))
max_path_len,max_path = find_max_path(matrix)
print("Max by search:" + str(max_path_len) + " and path:" + str(max_path))

Eager value:56 and path:[0, 1, 4, 2, 3, 0]
Min by search:48 and path:[0, 1, 3, 4, 2, 0]
Max by search:88 and path:[0, 3, 2, 1, 4, 0]


In [ ]:
def make_matrix(size, seed=23):
 np.random.seed(seed)
 rand_matrix = np.zeros((size, size))
 for i in range(size):
  for j in range(i, size):
    rand_matrix[i, j] = np.random.randint(0, 50)
    rand_matrix[j, i] = rand_matrix[i, j]
 return rand_matrix

matrix = make_matrix(10)
eager_path,min_eager = eager_algorithm(matrix)
print("Eager value:" + str(min_eager) + " and path:" + str(eager_path))
min_path_len,min_path = find_min_path(matrix)
print("Min by search:" + str(min_path_len) + " and path:" + str(min_path))
max_path_len,max_path = find_max_path(matrix)
print("Max by search:" + str(max_path_len) + " and path:" + str(max_path))

Eager value:123.0 and path:[0, 3, 2, 4, 5, 6, 7, 9, 8, 1, 0]
Min by search:94.0 and path:[0, 3, 2, 4, 6, 5, 1, 8, 9, 7, 0]
Max by search:388.0 and path:[0, 2, 7, 3, 4, 1, 6, 8, 5, 9, 0]
